#' @title Plot the results of a simulation of the random effects
#' @name plotREsim
#' @description Plot the simulated random effects on a ggplot2 chart
#' @param data a data.frame generated by \code{\link{REsim}} with simulations of
#' the random effects of a \code{\link{merMod}}
#' @param scale a factor to multiply the effect standard deviation by, default is 1.96 for
#' 95\% confidence intervals
#' @param var a character value indicating the variable name in data of the
#' midpoint of the estimated interval, e.g. "mean" or "median"
#' @param sd a character value indicating the variable name in data of the
#' variance of the estimated interval, e.g. "sd"
#' @param sigmaScale a numeric value to divide the estimate and the standard
#' deviation by in the case of doing an effect size calculation
#' @param oddsRatio logical, should the parameters be converted to odds ratios
#' before plotting
#' @return a ggplot2 plot of the coefficient effects
#' @export
#' @import ggplot2
plotREsim <- function(dat, scale = 1.96, var = "median_eff",
                      sd = "sd_eff",
                      sigmaScale = NULL,
                      oddsRatio = FALSE, labs = NULL){
  if(!missing(sigmaScale)){
    dat[, sd] <- dat[, sd] / sigmaScale
    dat[, var] <- dat[, var] / sigmaScale
  }
  dat[, sd] <- dat[, sd] * scale
  dat[, "ymax"] <- dat[, var] + dat[, sd]
  dat[, "ymin"] <- dat[, var] - dat[, sd]
  hlineInt <- 0
  if(oddsRatio == TRUE){
    dat[, "ymax"] <- exp(dat[, "ymax"])
    dat[, var] <- exp(dat[, var])
    dat[, "ymin"] <- exp(dat[, "ymin"])
    hlineInt <- 1
  }
  if(!missing(labs)){
    xlabs.tmp <- element_text(face = "bold")
    xvar <- labs
  } else {
    xlabs.tmp <- element_blank()
    xvar <- "id"
  }

  dat[order(dat[, var]), "id"] <- c(1:nrow(dat))
  ggplot(dat, aes_string(x = xvar, y = var, ymax = "ymax",
                         ymin = "ymin")) +
    geom_pointrange(alpha = I(0.25)) + theme_bw() + geom_point() +
    labs(x = "Group", y = "Effect Range", title = "Effect Ranges") +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
          axis.text.x = xlabs.tmp, axis.ticks.x = element_blank()) +
    geom_hline(yintercept = hlineInt, color = I("red"), size = I(1.1)) +
    facet_grid(effect ~ level)
}

#' @title Plot the results of a simulation of the fixed effects
#' @name plotFEsim
#' @description Plot the simulated fixed effects on a ggplot2 chart
#' @param data a data.frame generated by \code{\link{FEsim}} with simulations of
#' the fixed effects of a \code{\link{merMod}}
#' @param scale a factor to multiply the effect standard deviation by, default is 1.96 for
#' 95\% confidence intervals
#' @param var a character value indicating the variable name in data of the
#' midpoint of the estimated interval, e.g. "mean" or "median"
#' @param sd a character value indicating the variable name in data of the
#' variance of the estimated interval, e.g."sd"
#' @param intercept logical, should the intercept be included, default is FALSE
#' @param sigmaScale a numeric value to divide the estimate and the standard
#' deviation by in the case of doing an effect size calculation
#' @param oddsRatio logical, should the parameters be converted to odds ratios
#' before plotting
#' @return a ggplot2 plot of the coefficient effects
#' @export
#' @import ggplot2
plotFEsim <- function(data, scale = 1.96, var = "median_eff", sd = "sd_eff",
                      intercept = FALSE, sigmaScale = NULL, oddsRatio = FALSE){
  if(!missing(sigmaScale)){
    data[, sd] <- data[, sd] / sigmaScale
    data[, var] <- data[, var] / sigmaScale
  }
  if(intercept == FALSE){
    data <- data[data$variable != "(Intercept)", ]
  }
  data[, sd] <- data[, sd] * scale
  data[, "ymax"] <- data[, var] + data[, sd]
  data[, "ymin"] <- data[, var] - data[, sd]
  hlineInt <- 0
  if(oddsRatio == TRUE){
    data[, "ymax"] <- exp(data[, "ymax"])
    data[, var] <- exp(data[, var])
    data[, "ymin"] <- exp(data[, "ymin"])
    hlineInt <- 1
  }
  xvar <- "variable"
  data$variable <- as.character(data$variable)
  data$variable <- factor(data$variable , levels = data[order(data[, var]), 1])
  ggplot(aes_string(x = xvar, y = var, ymax = "ymax",
                    ymin = "ymin"),
         data = data) + geom_point(size=I(3)) +
    geom_errorbar(width = 0.2) + geom_hline(yintercept = hlineInt, color = I("red")) +
    coord_flip() +
    theme_bw()
}

