#' @title Plot the results of a simulation of the random effects
#' @name plotREsim
#' @description Plot the simulated random effects on a ggplot2 chart
#' @param data a data.frame generated by \code{\link{REsim}} with simulations of
#' the random effects of a \code{\link{merMod}}
#' @param scale a factor to multiply the effect standard deviation by, default is 1.96 for
#' 95\% confidence intervals
#' @param var a character value indicating the variable name in data of the
#' midpoint of the estimated interval, e.g. "mean" or "median"
#' @param sd a character value indicating the variable name in data of the
#' variance of the estimated interval, e.g. "sd"
#' @param sigmaScale a numeric value to divide the estimate and the standard
#' deviation by in the case of doing an effect size calculation
#' @param oddsRatio logical, should the parameters be converted to odds ratios
#' before plotting
#' @param labs logical, include the labels of the groups on the x-axis
#' @return a ggplot2 plot of the coefficient effects
#' @examples
#'  require(ggplot2); require(lme4);
#'  fm1 <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
#'  (p1 <- plotREsim(REsim(fm1)))
#' @export
#' @import ggplot2
plotREsim <- function(data, scale = 1.96, var = "median_eff",
                      sd = "sd_eff",
                      sigmaScale = NULL,
                      oddsRatio = FALSE, labs = FALSE){
  if(!missing(sigmaScale)){
    data[, sd] <- data[, sd] / sigmaScale
    data[, var] <- data[, var] / sigmaScale
  }
  data[, sd] <- data[, sd] * scale
  data[, "ymax"] <- data[, var] + data[, sd]
  data[, "ymin"] <- data[, var] - data[, sd]
  hlineInt <- 0
  if(oddsRatio == TRUE){
    data[, "ymax"] <- exp(data[, "ymax"])
    data[, var] <- exp(data[, var])
    data[, "ymin"] <- exp(data[, "ymin"])
    hlineInt <- 1
  }
  if(labs == TRUE){
    xlabs.tmp <- element_text(face = "bold", angle=90, vjust=.5)
    data <- dplyr::ungroup(dplyr::arrange_(dplyr::group_by(data, level, effect), var))
    data[,"xvar"] <- factor(data$group, levels=unique(data$group))
  } else {
    xlabs.tmp <- element_blank()
    data <- dplyr::ungroup(dplyr::mutate(dplyr::arrange_(dplyr::group_by(data, level, effect), var), xvar=dplyr::row_number(effect)))
  }

  ggplot(data, aes_string(x = "xvar", y = var, ymax = "ymax", ymin = "ymin")) +
    geom_hline(yintercept = hlineInt, color = I("red"), size = I(1.1)) +
    geom_pointrange(alpha = I(0.25)) +
    geom_point() +
    labs(x = "Group", y = "Effect Range", title = "Effect Ranges") +
    theme_bw() +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.text.x = xlabs.tmp,
          axis.ticks.x = element_blank()) +
    facet_grid(effect ~ level, scales = "free_x")
}

#' @title Plot the results of a simulation of the fixed effects
#' @name plotFEsim
#' @description Plot the simulated fixed effects on a ggplot2 chart
#' @param data a data.frame generated by \code{\link{FEsim}} with simulations of
#' the fixed effects of a \code{\link{merMod}}
#' @param scale a factor to multiply the effect standard deviation by, default is 1.96 for
#' 95\% confidence intervals
#' @param var a character value indicating the variable name in data of the
#' midpoint of the estimated interval, e.g. "mean" or "median"
#' @param sd a character value indicating the variable name in data of the
#' variance of the estimated interval, e.g."sd"
#' @param intercept logical, should the intercept be included, default is FALSE
#' @param sigmaScale a numeric value to divide the estimate and the standard
#' deviation by in the case of doing an effect size calculation
#' @param oddsRatio logical, should the parameters be converted to odds ratios
#' before plotting
#' @return a ggplot2 plot of the coefficient effects
#' @examples
#'  require(ggplot2); require(lme4);
#'  fm1 <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
#'  (p1 <- plotFEsim(FEsim(fm1)))
#' @export
#' @import ggplot2
plotFEsim <- function(data, scale = 1.96, var = "median_eff", sd = "sd_eff",
                      intercept = FALSE, sigmaScale = NULL, oddsRatio = FALSE){
  if(!missing(sigmaScale)){
    data[, sd] <- data[, sd] / sigmaScale
    data[, var] <- data[, var] / sigmaScale
  }
  if(intercept == FALSE){
    data <- data[data$variable != "(Intercept)", ]
  }
  data[, sd] <- data[, sd] * scale
  data[, "ymax"] <- data[, var] + data[, sd]
  data[, "ymin"] <- data[, var] - data[, sd]
  hlineInt <- 0
  if(oddsRatio == TRUE){
    data[, "ymax"] <- exp(data[, "ymax"])
    data[, var] <- exp(data[, var])
    data[, "ymin"] <- exp(data[, "ymin"])
    hlineInt <- 1
  }
  xvar <- "variable"
  data$variable <- as.character(data$variable)
  data$variable <- factor(data$variable , levels = data[order(data[, var]), 1])
  ggplot(aes_string(x = xvar, y = var, ymax = "ymax",
                    ymin = "ymin"),
         data = data) + geom_point(size=I(3)) +
    geom_errorbar(width = 0.2) + geom_hline(yintercept = hlineInt, color = I("red")) +
    coord_flip() +
    theme_bw()
}

