#' @title Plot the results of a simulation of the random effects
#' @name plotREsim
#' @description Plot the simulated random effects on a ggplot2 chart. Points that
#' are distinguishable from zero (i.e. the confidence band based on \code{level}
#' does not cross the red line) are highlighted. Currently, the plots are ordered
#' according to the grouping factor.
#' @param data a data.frame generated by \code{\link[merTools]{REsim}} with simulations of
#' the random effects of a \code{\link[lme4]{merMod}}
#' @param level the width of the confidence interval
#' @param stat a character value indicating the variable name in data of the
#' midpoint of the estimated interval, e.g. "mean" or "median"
#' @param sd a logical indicating whether or not to plot error bars around
#' the estimates (default is TRUE). Calculates the width of the error bars
#' based on \code{level} and the variable named "sd" in \code{data}
#' @param sigmaScale a numeric value to divide the estimate and the standard
#' deviation by in the case of doing an effect size calculation
#' @param oddsRatio logical, should the parameters be converted to odds ratios
#' before plotting
#' @param labs logical, include the labels of the groups on the x-axis
#' @param facet Accepts either logical (\code{TRUE}) or \code{list} to specify which
#' random effects to plot. If \code{TRUE}, facets by both \code{groupFctr} and \code{term}.
#' If \code{list} selects the panel specified by the named elements of the list
#' @return a ggplot2 plot of the coefficient effects
#' @examples
#' \donttest{
#'  fm1 <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
#'  (p1 <- plotREsim(REsim(fm1)))
#'  #Plot just the random effects for the Days slope
#'  (p2 <- plotREsim(REsim(fm1), facet= list(groupFctr= "Subject", term= "Days")))
#'  }
#' @export
#' @import ggplot2
plotREsim <- function(data, level = 0.95, stat = "median", sd = TRUE,
                      sigmaScale = NULL, oddsRatio = FALSE, labs = FALSE,
                      facet= TRUE){
  # error checking
  plot_sim_error_chks(type= "RE", level= level, stat= stat, sd= sd, sigmaScale= sigmaScale,
                      oddsRatio= oddsRatio, labs= labs, facet= facet)
  # check for faceting
  facet_logical <- is.logical(facet)
  if (!facet_logical) {
    data <- data[data$groupFctr == facet[[1]] & data$term == facet[[2]], ]
  }

  if(!missing(sigmaScale)){
    data[, "sd"] <- data[, "sd"] / sigmaScale
    data[, stat] <- data[, stat] / sigmaScale
  }
  data[, "sd"] <- data[, "sd"] * qnorm(1-((1-level)/2))
  data[, "ymax"] <- data[, stat] + data[, "sd"]
  data[, "ymin"] <- data[, stat] - data[, "sd"]
  data[, "sig"] <- data[, "ymin"] > 0 | data[, "ymax"] < 0
  hlineInt <- 0
  if(oddsRatio == TRUE){
    data[, "ymax"] <- exp(data[, "ymax"])
    data[, stat] <- exp(data[, stat])
    data[, "ymin"] <- exp(data[, "ymin"])
    hlineInt <- 1
  }
  data <- data[order(data[,"groupFctr"], data[,"term"], data[,stat]),]
  rownames(data) <- 1:nrow(data)
  data[,"xvar"] <- factor(paste(data$groupFctr, data$groupID, sep=""),
                          levels=unique(paste(data$groupFctr,data$groupID, sep="")),
                          ordered=TRUE)
  if(labs == TRUE){
    xlabs.tmp <- element_text(face = "bold", angle=90, vjust=.5)
  } else {
    data[,"xvar"] <- as.numeric(data[,"xvar"])
    xlabs.tmp <- element_blank()
  }

  p <- ggplot(data, aes(x = .data[["xvar"]], y = .data[[stat]], ymax = .data[["ymax"]], ymin = .data[["ymin"]])) +
         geom_hline(yintercept = hlineInt, color = I("red"), linewidth = I(1.1)) +
         geom_point(color="gray75", alpha=1/(nrow(data)^.33), size=I(0.5)) +
         geom_point(data=subset(data, sig==TRUE), size=I(3)) +
         labs(x = "Group", y = "Effect Range", title = "Effect Ranges") +
         theme_bw() +
         theme(panel.grid.major = element_blank(),
               panel.grid.minor = element_blank(),
               axis.text.x = xlabs.tmp,
               axis.ticks.x = element_blank())
  if (sd) {
    p <- p +
      geom_pointrange(alpha = 1/(nrow(data)^.33)) +
      geom_pointrange(data=subset(data, sig==TRUE), alpha = 0.25)
  }
  # check facet
  if (facet_logical) {
    return(p + facet_grid(term ~ groupFctr, scales = "free_x"))
  } else {
    return(p)
  }
}

#' @title Plot the results of a simulation of the fixed effects
#' @name plotFEsim
#' @description Plot the simulated fixed effects on a ggplot2 chart
#' @param data a data.frame generated by \code{\link{FEsim}} with simulations of
#' the fixed effects of a \code{\link[lme4]{merMod}}
#' @param level the width of the confidence interval
#' @param stat a character value indicating the variable name in data of the
#' midpoint of the estimated interval, e.g. "mean" or "median"
#' @param sd logical, indicating whether or not to plot error bars around
#' the estimates (default is TRUE). Calculates the width of the error bars
#' based on \code{level} and the variable named "sd" in \code{data}
#' @param intercept logical, should the intercept be included, default is FALSE
#' @param sigmaScale a numeric value to divide the estimate and the standard
#' deviation by in the case of doing an effect size calculation
#' @param oddsRatio logical, should the parameters be converted to odds ratios
#' before plotting
#' @return a ggplot2 plot of the coefficient effects
#' @examples
#'  fm1 <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
#'  (p1 <- plotFEsim(FEsim(fm1)))
#' @export
#' @import ggplot2
plotFEsim <- function(data, level=0.95, stat = "median", sd = TRUE,
                      intercept = FALSE, sigmaScale = NULL, oddsRatio = FALSE){
  # error checking
  plot_sim_error_chks(type= "FE", level= level, stat= stat, sd= sd, sigmaScale= sigmaScale,
                      oddsRatio= oddsRatio, labs= TRUE, facet= TRUE)

  if(!missing(sigmaScale)){
    data[, "sd"] <- data[, "sd"] / sigmaScale
    data[, stat] <- data[, stat] / sigmaScale
  }
  if(intercept == FALSE){
    data <- data[data$term != "(Intercept)", ]
  }
  data[, "sd"] <- data[, "sd"] * qnorm(1-((1-level)/2))
  data[, "ymax"] <- data[, stat] + data[, "sd"]
  data[, "ymin"] <- data[, stat] - data[, "sd"]
  hlineInt <- 0
  if(oddsRatio == TRUE){
    data[, "ymax"] <- exp(data[, "ymax"])
    data[, stat] <- exp(data[, stat])
    data[, "ymin"] <- exp(data[, "ymin"])
    hlineInt <- 1
  }
  # Flag terms whose interval excludes the null line so they can be highlighted,
  # mirroring the convention used by plotREsim() (#85).
  data[, "sig"] <- data[, "ymin"] > hlineInt | data[, "ymax"] < hlineInt
  xvar <- "term"
  data$term <- as.character(data$term)
  data$term <- factor(data$term , levels = data[order(data[, stat]), 1])
  p <- ggplot(aes(x = .data[[xvar]], y = .data[[stat]], ymax = .data[["ymax"]],
                  ymin = .data[["ymin"]], color = .data[["sig"]]), data = data) +
    geom_hline(yintercept = hlineInt, color = "red", linetype = 2) +
    geom_point(size = I(3)) +
    scale_color_manual(values = c(`FALSE` = "grey60", `TRUE` = "black"),
                       guide = "none") +
    coord_flip() +
    labs(x = "Fixed effect", y = "Estimate") +
    theme_minimal(base_size = 12) +
    theme(panel.grid.minor = element_blank())
  if (sd) {
    p <- p + geom_errorbar(width = 0.2)
  }
  p
}

#' @title Plot the impact of grouping-factor levels on predictions
#' @name plotREimpact
#' @description Plot the output of one or more \code{\link{REimpact}} calls on a
#' single chart. Each point is the weighted-average fitted value for a bin of
#' the expected-rank distribution of a grouping factor, with a confidence
#' interval derived from the weighted standard error. Supplying a named list of
#' \code{REimpact} results overlays them on the same axes -- for example to
#' compare the influence of two different grouping factors, or the same factor
#' across two models -- which previously required hand-assembling the data
#' frames (#84).
#' @param data either a single data.frame produced by \code{\link{REimpact}},
#' or a named list of such data.frames. When a named list is supplied the names
#' are used to colour and label the series.
#' @param level the width of the confidence interval (default 0.95).
#' @param facet logical, facet the plot by \code{case} (default \code{TRUE}).
#' @param point_size numeric size of the plotted central points.
#' @return a ggplot2 object.
#' @seealso \code{\link{REimpact}}
#' @examples
#' \donttest{
#'  m1 <- lmer(Reaction ~ Days + (1 | Subject), sleepstudy)
#'  imp <- REimpact(m1, newdata = sleepstudy[1, ], groupFctr = "Subject",
#'                  breaks = 4)
#'  plotREimpact(imp)
#'
#'  # Compare two grouping factors on the same chart
#'  g1 <- lmer(y ~ lectage + studage + (1 | d) + (1 | s), data = InstEval)
#'  d_eff <- REimpact(g1, newdata = InstEval[1, ], groupFctr = "d", breaks = 4)
#'  s_eff <- REimpact(g1, newdata = InstEval[1, ], groupFctr = "s", breaks = 4)
#'  plotREimpact(list("Instructor (d)" = d_eff, "Student (s)" = s_eff))
#'  }
#' @export
#' @import ggplot2
plotREimpact <- function(data, level = 0.95, facet = TRUE, point_size = 2.5) {
  if (!is.numeric(level) || length(level) != 1 || level <= 0 || level >= 1) {
    stop("`level` must be a single number between 0 and 1.", call. = FALSE)
  }
  # Normalize input to a single data.frame carrying a `series` label.
  if (is.data.frame(data)) {
    data[["series"]] <- "REimpact"
    multi <- FALSE
  } else if (is.list(data)) {
    if (length(data) == 0L) stop("`data` is an empty list.", call. = FALSE)
    nm <- names(data)
    if (is.null(nm) || any(nm == "" | is.na(nm))) {
      nm <- paste0("series ", seq_along(data))
    }
    data <- do.call(rbind, Map(function(d, s) {
      if (!is.data.frame(d)) {
        stop("Each element of `data` must be a REimpact() data.frame.",
             call. = FALSE)
      }
      d[["series"]] <- s
      d
    }, data, nm))
    multi <- length(unique(data[["series"]])) > 1L
  } else {
    stop("`data` must be a REimpact() data.frame or a (named) list of them.",
         call. = FALSE)
  }

  req_cols <- c("case", "bin", "AvgFit", "AvgFitSE")
  missing_cols <- setdiff(req_cols, names(data))
  if (length(missing_cols) > 0) {
    stop("`data` does not look like REimpact() output; missing column(s): ",
         paste(missing_cols, collapse = ", "), call. = FALSE)
  }

  z <- qnorm(1 - (1 - level) / 2)
  data[["ymin"]] <- data[["AvgFit"]] - z * data[["AvgFitSE"]]
  data[["ymax"]] <- data[["AvgFit"]] + z * data[["AvgFitSE"]]
  data[["bin"]] <- factor(data[["bin"]])

  p <- ggplot(data, aes(x = .data[["bin"]], y = .data[["AvgFit"]],
                        ymin = .data[["ymin"]], ymax = .data[["ymax"]])) +
    labs(x = "Expected rank bin (low to high)",
         y = "Average fitted value",
         title = "Impact of grouping-factor levels on the outcome") +
    theme_minimal(base_size = 12) +
    theme(panel.grid.minor = element_blank(),
          legend.position = "top")

  if (multi) {
    dodge <- position_dodge(width = 0.5)
    p <- p +
      geom_pointrange(aes(color = .data[["series"]]), position = dodge,
                      size = point_size / 4, fatten = point_size) +
      labs(color = NULL)
  } else {
    p <- p + geom_pointrange(size = point_size / 4, fatten = point_size)
  }

  if (facet) {
    p <- p + facet_wrap(~ case)
  }
  p
}

