# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppeigen_invert_matrix <- function(A) {
    .Call('merTools_rcppeigen_invert_matrix', PACKAGE = 'merTools', A)
}

rcppeigen_get_diag <- function(A) {
    .Call('merTools_rcppeigen_get_diag', PACKAGE = 'merTools', A)
}

rcppeigen_get_det <- function(A) {
    .Call('merTools_rcppeigen_get_det', PACKAGE = 'merTools', A)
}

#' @title
#' find the Cholesky decomposition of a matrix with RcppEigen
#' @description
#' Speed up Cholesky SPD matrix decomposition
#' @param A a matrix to decompose
#' @export
rcppeigen_get_chol <- function(A) {
    .Call('merTools_rcppeigen_get_chol', PACKAGE = 'merTools', A)
}

