# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' Faster multivariate normal sampling
#' @description
#' Speed up sampling from multivariate normal using C++
#' @param n number of samples to draw
#' @param mu vector of means to use for the distribution
#' @param sigma matrix of sigma values for distribution
#'
#' @export
mvrnormArma <- function(n, mu, sigma) {
    .Call('merTools_mvrnormArma', PACKAGE = 'merTools', n, mu, sigma)
}

